### ISSUE TITLE
AttributeStorage update for 1.8

### ISSUE THREAD

**Issue by Kainzo** [Steveice10/OpenNBT#1]
Was there any eta on this? and sorry if this happens to be in the wrong repo.

**Comment by Steveice10** [comment]
It's been a while, so my memory may have slipped. Can you explain what "AttributeStorage update for 1.8" is?

**Comment by Kainzo** [comment]
was asking for the issues we're having with serialization / etc in
https://github.com/Herocraft/Backpack
and a custom project that adds NBT custom data onto items.
