### ISSUE TITLE
NBT Specification

### ISSUE THREAD

**Issue by milse113** [Steveice10/OpenNBT#16]
While this isn't strictly an issue relating to the project, I was wondering what NBT specification/documentation this is based on?

I'm working on implementing a similar library in rust and the Wiki.VG specification is breaking on the JoinGame packet

**Comment by Steveice10** [comment]
There is no one specification I can point to as having based this off of. I'm pretty sure it was just based off whatever reference info I could find out there, plus testing it against known good files.

I know the Minecraft Wiki also has a page on NBT. Feel free to also use this library as a reference if you want.
