### ISSUE TITLE
Tag.equals fails when Tag name is null

### ISSUE THREAD

**Issue by yawkat** [Steveice10/OpenNBT#5]

**Comment by Steveice10** [comment]
Why do you have a tag with a null name?

**Comment by yawkat** [comment]
List items can have a null tag name. Do you recommend an empty string instead?

**Comment by Steveice10** [comment]
Yes. I'm pretty sure that's how I do it when reading tag lists.

**Comment by yawkat** [comment]
Alright :) thank you
