### ISSUE TITLE
Ambiguous method call

### ISSUE THREAD

**Issue by MylesIsCool** [Steveice10/OpenNBT#7]
Hi,

We use your project in ViaVersion due to you changing the method signature we get compilation errors.
```
[ERROR] /home/travis/build/MylesIsCool/ViaVersion/common/src/main/java/us/myles/ViaVersion/api/type/types/minecraft/NBTType.java:[44,18] reference to writeTag is ambiguous
  both method writeTag(java.io.OutputStream,org.spacehq.opennbt.tag.builtin.Tag) in org.spacehq.opennbt.NBTIO and method writeTag(java.io.DataOutput,org.spacehq.opennbt.tag.builtin.Tag) in org.spacehq.opennbt.NBTIO match
```

Is there a chance of version bump & deploy to maven?

**Comment by Steveice10** [comment]
Cast to the one you want to use.

**Comment by MylesIsCool** [comment]
Maybe I was a bit unclear, the issue is we have some systems using an older version of your library and some using the latest.
This is because both are known as 1.0, so is there a chance you can version bump & deploy to maven because I consider the latest change a breaking one which is the issue.


Kind Regards
